---
- name: Configure ansible-node1
  hosts: lima_vms
  become: true

  roles:
    - nginx
    - node_exporter
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Copy using inline content
      copy:
        content: "This file configured with Ansible"
        dest: /etc/motd
